#! /bin/sh

MAKE=make

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ]; then mkdir work; fi
rm -rf work/lib

export NEDPATH=.:
EXTRA_INCLUDES="-I../simulations"
 
opp_test -g $OPT -v $TESTFILES || exit 1 
echo 
(cd work; opp_makemake -f --deep --no-deep-includes -i ../makefrag$EXTRA_INCLUDES; $MAKE) || exit 1
echo
opp_test -r $OPT -v $TESTFILES || exit 1
echo
echo Results can be found in ./work
